default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  timeout: 5000
  username: <%= ENV['MS_USERNAME'] %>
  password: <%= ENV['MS_PASSWORD'] %>
  host: <%= ENV['MS_HOST'] %>
  port: 3306

test:
  <<: *default
  database: user_test

development:
  <<: *default
  database: user_dev

production:
  <<: *default
  database: user
